#ifndef __RENDERKINGKONG_PREREQUISITES_HPP__
#define __RENDERKINGKONG_PREREQUISITES_HPP__

#include "./TypeDeclareUtils.hpp"

#undef  WIZ_CUSTOM_DECLARE_HELPER
#define WIZ_CUSTOM_DECLARE_HELPER                    RKK_DECLARE
#undef  WIZ_CUSTOM_DECLARE_HELPER_SIMPLE
#define WIZ_CUSTOM_DECLARE_HELPER_SIMPLE             RKK_DECLARE_SIMPLE
#undef  WIZ_CUSTOM_DECLARE_HELPER_PTR
#define WIZ_CUSTOM_DECLARE_HELPER_PTR                RKK_DECLARE_PTR

#undef  WIZ_CUSTOM_DECLARE_HELPER_CONTAINER
#define WIZ_CUSTOM_DECLARE_HELPER_CONTAINER          RKK_DECLARE
#undef  WIZ_CUSTOM_DECLARE_HELPER_ITERATOR
#define WIZ_CUSTOM_DECLARE_HELPER_ITERATOR           RKK_DECLARE_ITER
#undef  WIZ_CUSTOM_DECLARE_HELPER_ITERATOR_CONST
#define WIZ_CUSTOM_DECLARE_HELPER_ITERATOR_CONST     RKK_DECLARE_ITER_CONST

#include "../../../WIZ_Library/Include/WizCustomDeclareHelper.hpp"

#endif /// __RENDERKINGKONG_PREREQUISITES_HPP__
